export interface RenewalObject {
  id: string;
  practitioner_uuid: string;
  deleted_at: string | null;
  uuid: string;
  registration_number: string;
  deleted_by: string;
  deleted: string;
  modified_by: string;
  created_by: string;
  created_on: string;
  modified_on: string;
  receipt: string;
  qr_code: string;
  qr_text: string;
  expiry: string;
  specialty: string;
  place_of_work: string;
  region: string;
  institution_type: string;
  district: string;
  status: "Approved" | "Pending Payment" | "Pending Approval";
  payment_date: string;
  payment_file: string;
  payment_file_date: string;
  subspecialty: string;
  college_membership: string;
  payment_invoice_number: string;
  first_name: string;
  middle_name: string;
  last_name: string;
  title: string;
  maiden_name: string;
  marital_status: string;
  picture: string;
  year: string;
  practitioner_type: "Doctor" | "Physician Assistant";
  register_type: "Permanent" | "Temporary" | "Provisional";
}
